# not being used as of the moment
name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE.md
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository_owner == 'exyleio' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
